const informa = (prefix, sender) => {
	return `
	*_⚡ LOSER BOTS ⚡_*
*_❗INFORMAÇÕES❗_*

*LOSER BOTS É UM BOT DE WHATSAPP PARA FAZER STICKERS/FIGURINHAS COM COMANDOS, E PARA MONITORAR GRUPOS DE WHATSAPP, APENAS SE DIVIRTAM-SE COM MULTI FUNÇÕES*
*🦋 QUALQUER DUVIDA/BUGS CHAME O CRIADOR: WA.me/558499034946*
`
}
exports.informa = informa
